

version: '3.8'
services:

  celery:
    restart: always
    build:
      context: .
    command: celery -A DJANGO_PROJECT worker -l info
    volumes:
      - .:/app
    environment:
      - DB_HOST=${REDIS_HOST}
      - DB_NAME=${REDIS_PORT}
    depends_on:
      - django
      - db
      - redis
    networks:
      my_networks:
        ipv4_address: 172.28.1.2

  django:
    build: .
#    image: sheracore/interview_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=DJANGO_PROJECT.settings
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      my_networks:
        ipv4_address: 172.28.1.1

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_DATABASE_USER}
      - MYSQL_PASSWORD=${MYSQL_DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      my_networks:
        ipv4_address: 172.28.1.3

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      environment:
        - DB_HOST=${REDIS_HOST}
        - DB_NAME=${REDIS_PORT}
      networks:
        my_networks:
          ipv4_address: 172.28.1.4

networks:
    my_networks:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
