name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    env:
#      MY_ENV_VAR: .env
      MYSQL_DATABASE_HOST: ${{ secrets.MYSQL_DATABASE_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_DATABASE_ROOT_PASSWORD: ${{ secrets.MYSQL_DATABASE_ROOT_PASSWORD }}
      MYSQL_DATABASE_USER: ${{ secrets.MYSQL_DATABASE_USER }}
      MYSQL_DATABASE_PASSWORD: ${{ secrets.MYSQL_DATABASE_PASSWORD }}
      MYSQL_DATABASE_PORT: ${{ secrets.MYSQL_DATABASE_PORT }}
      CELERY_ID: ${{ secrets.CELERY_ID }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
      DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
      CDN_URL: ${{ secrets.CDN_URL }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Run Tests
#      run: |
#        python manage.py test
        
#    - name: Build and Push Docker Image
#      uses: mr-smithers-excellent/docker-build-push@v6
#      with:
#        image: sheracore/interview_backend
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run Docker-Compose
      run: docker-compose up -d

    - name: Build and Push Docker-Compose Image
      run: |
        docker-compose build
        docker-compose push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
